// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCk8P2RVmLpiFQdKOK14qwZdQAp8bZEuA',
    appId: '1:433297876025:web:31cf6fbb6d478aecc899e8',
    messagingSenderId: '433297876025',
    projectId: 'p-doctors-clinics',
    authDomain: 'p-doctors-clinics.firebaseapp.com',
    storageBucket: 'p-doctors-clinics.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5nHis-dNHK9e-LZcZERnSMry8WEEhz-g',
    appId: '1:433297876025:android:448cb08f475a7f0dc899e8',
    messagingSenderId: '433297876025',
    projectId: 'p-doctors-clinics',
    storageBucket: 'p-doctors-clinics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrjp-NsOL7gBdD-Td7R5bszwlR0OZYj6o',
    appId: '1:433297876025:ios:e2738672ce6498d4c899e8',
    messagingSenderId: '433297876025',
    projectId: 'p-doctors-clinics',
    storageBucket: 'p-doctors-clinics.firebasestorage.app',
    iosBundleId: 'com.clinics.clinicsBooking',
  );
}
